config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users do
    collection do 
      get 'add_friend/:id', to: 'users#send_friend_request', as: 'add_friend'
      get 'accept_friend', to: 'users#accept_friend_request', as: 'accept_friend'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :edit, :update, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  def user_id
    self.user.id
  end

  def created_at_string
    zone = ActiveSupport::TimeZone.new("Central Time (US & Canada)")
    zoned_time = self.created_at.in_time_zone(zone)
    "#{zoned_time.strftime('%B %e, %Y')} at #{zoned_time.strftime('%l:%M %P')}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :user_name, presence: true, uniqueness: true

  has_many :posts
  has_many :friend_requests
  has_and_belongs_to_many(:friends, 
                          :join_table => "friends", 
                          :foreign_key => "user_a_id", 
                          :association_foreign_key => "user_b_id", 
                          :class_name => "User" 
                        )

  def to_string
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_user, only: [:create, :update, :destroy]
  #before_action :current_user, only: [:create, :update, :destroy]
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts/new
  def new
    if session[:user_id]
      @post = Post.new
    else
      redirect_to root_path, notice: "You must be logged in to create a post!"
    end
  end

  # GET /posts/1/edit
  def edit
    if !session[:user_id]
      redirect_to root_path, notice: "You must be logged in to edit a post!"
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: session[:user_id]))
    respond_to do |format|
      if @post.save
        format.html { redirect_to @user, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @user, notice: 'Successfully edited your post!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end

    # Get current user.
    def get_user
      @user = User.find(session[:user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_user_name(params[:user_name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user, notice: "You have been successfully logged in!"
    else
      flash[:alert] = "You have entered an invalid username or password. Please try again."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have been successfully logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :send_friend_request]
  before_action :set_session_user

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @feed_posts = (@user.friends.map{|u| u.posts}.flatten + @user.posts)
    @feed_posts.sort_by! {|post| post.created_at}.reverse! 
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if @user.id != session[:user_id]
      redirect_to @session_user, notice: 'Edit failed, unauthorized access.'
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :root, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.id != session[:user_id]
      redirect_to @session_user, notice: 'Delete failed, unauthorized access.'
    else
      @user.posts.each {|p| p.destroy}
      @user.destroy
      @current_user = nil
      respond_to do |format|
        format.html { redirect_to root_url, notice: 'Your account has been deleted.' }
        format.json { head :no_content }
      end
    end
  end

  def send_friend_request
    FriendRequest.create(sender_id: @session_user.id, user_id: @user.id)
    redirect_to @session_user, notice: 'Friend request sent!'
  end

  def accept_friend_request
    sender = User.find(params[:sender_id])
    @session_user.friends << sender
    sender.friends << @session_user
    FriendRequest.find_by(sender_id: params[:sender_id]).destroy
    redirect_to @session_user, notice: 'Friend request accepted!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Get session id information.
    def set_session_user
      if session[:user_id]
        @session_user ||= User.find(session[:user_id])
      else
        @session_user = nil
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<p id='notice'><%= notice %></p>
<h1>Welcome to Knockoff Facebook!</h1>
<% if current_user %>
  Logged in as <%= current_user.user_name %>.
  <p><%= button_to "Home Page", users_path, :method => 'get' %></p>
  <p><%= button_to "Log out", logout_path, :method => 'get' %></p>
<% else %>
  <p><%= button_to "Log in", login_path, :method => 'get' %></p>
  <p>
    &nbsp;For new users, <br><br>
    <%= button_to "Sign up", signup_path, :method => 'get' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<% @users.each do |user| %>
  <p><%= link_to user.to_string, user %></p>
<% end %>
<br>

<%= link_to "My Profile", @session_user %> |
<%= link_to "Log out", logout_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= "#{@user.to_string}'s profile page" %></h1>
 
<h2><%= "News feed:" %></h2>
<% @feed_posts.each do |post| %>
  <p>
    <h3><%= post.title %></h3>
    <p><%= post.content %></p>
    <p>&emsp;--<%= "Posted by #{post.user.to_string} on #{post.created_at_string}" %></p>
    <% if @session_user.id == post.user_id %>
      <p>
        -- 
        <%= link_to 'Edit', edit_post_path(post) %> 
        --
        <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %> 
        --
      </p>
    <% end %>
  </p>
<% end %>

<% if @session_user.id == @user.id %>
  <h2>Your friends:</h2>
  <% @user.friends.each do |friend| %>
    <p><%= link_to friend.to_string, friend %></p>
  <% end %>
  <h2>Your friend requests:</h2>
  <% @user.friend_requests.each do |request| %>
    <p>
      <%= request.sender.to_string %>
      <%= button_to "Accept friend request", accept_friend_users_path, :method => "get", params: {sender_id: request.sender.id} %>
    </p>
  <% end %>
<% end %>

<% if @session_user.id == @user.id %>
  <%= link_to 'New Post', new_post_path %> |
  <%= link_to 'Edit Profile', edit_user_path(@user) %> |
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% elsif !@session_user.friends.include?(@user) %>
  <%= link_to "Add Friend", add_friend_users_path %>|
<% end %>
<% if @session_user.id != @user.id %>
  <%= link_to "My Profile", @session_user %> |
<% end %>
<%= link_to "Home Page", users_path %> |
<%= link_to "Log out", logout_path %>